import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { twMerge } from 'tailwind-merge';
import { Providers } from './providers';
import MainNavBar from '@/components/main/navbar/MainNavBar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="h-[100dvh] bg-background light">
      <body className={twMerge(inter.className, 'h-[100dvh] w-full light')}>
        <Providers className="min-h-full bg-background text-foreground">
          <MainNavBar className="" />
          <main className="flex h-full flex-col">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
